### ISSUE TITLE
How to configure / initialize sdk for desktop

### ISSUE THREAD

**Issue by AlbRoehm** [TeamHubApp/firebase-kotlin-sdk#458]
Hi, I'm trying to use the firestore on a compose for desktop app. I do setup the Firebase as following and Authentication works just fine. But trying to fetch something from the firestore result in the error below. Is there anything i'm generally doing wrong?

Thanks 

```kotlin
fun main() = application {
    initializeFirebase()
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}

fun initializeFirebase() {
    FirebasePlatform.initializeFirebasePlatform(
        object : FirebasePlatform() {
            val storage = mutableMapOf<String, String>()
            override fun store(key: String, value: String) = storage.set(key, value)
            override fun retrieve(key: String) = storage[key]
            override fun clear(key: String) {
                storage.remove(key)
            }
            override fun log(msg: String) = println(msg)
        },
    )

    val options = FirebaseOptions(
        applicationId = "appId",
        apiKey = "apiKey",
        projectId = "id",
    )

    Firebase.initialize(Application(), options)
}

```

```
> Task :SuperlistDesktop:run
FirebaseApp Device unlocked: initializing all Firebase APIs for app [DEFAULT]
FirebaseAuth Calling onIdTokenChanged for <UserID> on listener com.google.firebase.firestore.auth.FirebaseAuthCredentialsProvider$$Lambda$217/0x00000008002cd820@31ff67ec
GooglePlayServicesUtil The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
GooglePlayServicesUtil app.teamhub.TeamHub requires the Google Play Store, but it is missing.
GooglePlayServicesUtil GooglePlayServices not available due to error 9
Firestore (24.10.0) [GrpcCallProvider]: Failed to update ssl context: com.google.android.gms.common.GooglePlayServicesNotAvailableException
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Internal error in Cloud Firestore (24.10.0).
	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:545)
	at android.os.Handler$post$1.invokeSuspend(Handler.kt:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@170c7357, Dispatchers.Main]
Caused by: java.lang.NoClassDefFoundError: android/database/sqlite/SQLiteTransactionListener
	at com.google.firebase.firestore.core.SQLiteComponentProvider.createPersistence(SQLiteComponentProvider.java:48)
	at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:149)
	at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:296)
	at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0(FirestoreClient.java:114)
	at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:444)
	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:330)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: android.database.sqlite.SQLiteTransactionListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 13 more
Firestore (24.10.0) [AsyncQueue]: Refused to enqueue task after panic
Caused by: java.lang.NoClassDefFoundError: android/database/sqlite/SQLiteTransactionListener

Caused by: java.lang.ClassNotFoundException: android.database.sqlite.SQLiteTransactionListener

Jan 14, 2024 11:32:06 PM io.grpc.okhttp.internal.Platform getAndroidSecurityProvider
WARNING: Unable to find Conscrypt
Firestore (24.10.0) [AsyncQueue]: Refused to enqueue task after panic
Unable to find Conscrypt

PersistentConnection pc_0 - Firebase Database connection was forcefully killed by the server. Will not attempt reconnect. Reason: Firebase error. Please ensure that you have the URL of your Firebase Realtime Database instance configured correctly.
```

**Comment by nbransby** [comment]
Solution here: https://github.com/GitLiveApp/firebase-java-sdk/blob/master/README.md#cloud-firestore-does-not-support-offline-persistence-and-should-be-setup-as-follows
